#!/usr/bin/env python
# -*- coding: UTF-8 -*-

"""
GESTION ANNUAIRE - 13/02/2024
----------------------------------------------------
3.1. ANNUAIRE_0 – CONDITIONS, BOUCLES, TUPLE ET DICT
----------------------------------------------------

@Marysa RÉGENT
"""

from Annuaire_Pack import ContactLib

annuaire = {}
LARGEUR = 60

while True:
    print("=" * LARGEUR)
    print("Menu:".center(LARGEUR))
    print("=" * LARGEUR)
    print("1. Ajouter un nouveau contact")
    print("2. Afficher les contacts")
    print("3. Quitter l'application")
    print("=" * LARGEUR)

    choix = input("Choisissez une option (1, 2 ou 3) : ")

    if choix == '1':
        ContactLib.addContact(annuaire)
    elif choix == '2':
       ContactLib.displayContact(annuaire)
    elif choix == '3':
        print("Application quittée ")
        break
    else:
        print("Option non valide. Veuillez choisir 1, 2, ou 3.")